### ISSUE TITLE
Feature: log user notifications for followers when highlight is created

### ISSUE THREAD

**Issue by brandonroberts** [open-sauced/api#243]
### Type of feature

🍕 Feature

### Current behavior

API feature support for https://github.com/open-sauced/insights/issues/1108

When a new highlight is created, this should:
- Retrieve the list of followers for the user who created the highlight (users_to_users_followers)
- Add a new notification for the follower to see to the (user_notifications) table

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by takanome-dev** [comment]
I started doing this and stopped it because was thinking about the action of retrieving the list of the followers for the user.

What if the user has 1000 followers or more, are we going to wait and add a notification for each user before returning the new highlight created or just return the highlight and not wait the creation of notifications?

Or maybe delegate that to some kind of workers? Or I don't have to worry about that yet 😅

**Comment by brandonroberts** [comment]
> 

That's a good problem to have in the future :-) We can ship what's reasonable and revisit if it becomes an issue. I think you can send a batch of inserts in one pass with TypeORM also.

**Comment by takanome-dev** [comment]
.take
